# sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'bigdecimal'
gem 'bson'
gem 'bundler-unload'
gem 'haml'
gem 'json'
gem 'mongo'
gem 'rack'
gem 'rack-protection'
gem 'rake'
gem 'rdoc'
gem 'rubygems-bundler'
gem 'rvm'
gem 'sinatra'
gem 'test-unit'
gem 'tilt'
gem 'zip'
#gem 'rails'
